version: '3.9'
services:
  backend:
    container_name: new-container
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - static_volume:/usr/app/static
    env_file:
      - backend/.env
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - mongo

  frontend:
    container_name: frontend-container
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 8007:3000
    volumes:
      - static_volume:/usr/frontend/build
      
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    volumes:
      - ./mongo:/data/db
    ports:
      - 127.0.0.1:27017:27017

  
volumes:
  static_volume:
